# Generated by Django 3.2.13 on 2023-02-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japfa_training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt_employee',
            old_name='nik',
            new_name='empid',
        ),
        migrations.RenameField(
            model_name='mt_employee',
            old_name='name',
            new_name='empname',
        ),
    ]
