# Generated by Django 3.2.13 on 2023-02-20 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('japfa_training', '0002_auto_20230217_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='mt_user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('mt_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, related_name='mt_user_mt_employee', to='japfa_training.mt_employee')),
            ],
            options={
                'verbose_name_plural': 'mt_user',
                'db_table': 'mt_user',
            },
        ),
    ]
